jobs:
  include:
  - stage: test
    language: node.js
    nodejs:
    - '10.11'
    before_install:
    - npm install -g swagger-cli
    before_script:
    - cd api/
    script:
    - swagger-cli validate api.yaml
    cache:
      directories:
      - node_modules
    if: (branch = develop) OR (branch = master)
    branches:
      only:
      - develop
      - master

  - stage: Build docker images
    name: SwaggerUI
    language: minimal
    services:
    - docker
    install:
    - docker pull teamd2018/swagger-ui-geo-rest:latest
    script:
    - docker build -t $DOCKERHUB_OWNER/swagger-ui-geo-rest:$TRAVIS_COMMIT -f swagger-ui.Dockerfile --cache-from teamd2018/swagger-ui-geo-rest:latest .
    - docker tag $DOCKERHUB_OWNER/swagger-ui-geo-rest:$TRAVIS_COMMIT $DOCKERHUB_OWNER/swagger-ui-geo-rest:latest
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_NAME" --password-stdin
    - docker push $DOCKERHUB_OWNER/swagger-ui-geo-rest
    if: branch = master
    branches:
      only:
      - master

  - stage: deploy
    language: bash
    deploy:
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: master
    - provider: script
      skip_cleanup: true
      script: bash deploy.sh 35.204.198.186
      on:
        branch: develop
    before_deploy:
    - openssl aes-256-cbc -K $encrypted_0cf875d8061b_key -iv $encrypted_0cf875d8061b_iv -in travis_key.enc -out travis_key -d
    if: branch = master
    branches:
      only:
      - master
