version: '3.5'
services:
  swagger-ui:
    image: teamd2018/swagger-ui-geo-rest:latest
    ports:
    - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - geo-rest
  elastic-admin:
    image: appbaseio/dejavu:2.0.0
    ports:
      - 1358:1358
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - geo-rest
  tarantool-admin:
    image: quay.io/basis-company/tarantool-admin
    ports:
      - 3310:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - geo-rest
networks:
  geo-rest:
      name: geo-rest
      external: true
