openapi: 3.0.0
info:
  version: "0.0.1"
  title: delivery-club-courier-monitor
  description: Delivery Club Courier Monitor
paths:
  /couriers:
    $ref: 'couriers.yml'
  /couriers/{courier_id}:
    $ref: 'courier_id.yml'
  /couriers/{courier_id}/orders/{order_id}:
    $ref: 'courier_order.yml'
  /couriers/{courier_id}/orders:
    $ref: 'courier_orders.yml'
  /couriers/{courier_id}/geo_history:
    $ref: 'courier_geo_history.yml'
  /suggestions/couriers:
    $ref: 'couriers_suggestion.yml'


components:
  parameters:
    DeliveryClubID:
      $ref: 'parameters.yml#/CourierID'
    OrderID:
      $ref: 'parameters.yml#/OrderID'
  schemas:
    CourierCreate:
      $ref: 'schemas.yml#/CourierCreate'
    CourierUpdate:
      $ref: 'schemas.yml#/CourierUpdate'
    Courier:
      $ref: 'schemas.yml#/Courier'
    OrderCreate:
      $ref: 'schemas.yml#/OrderCreate'
    OrderUpdate:
      $ref: 'schemas.yml#/OrderUpdate'
    Order:
      $ref: 'schemas.yml#/Order'
    Location:
      $ref: 'schemas.yml#/Location'
    Couriers:
      $ref: 'schemas.yml#/Couriers'
    Orders:
      $ref: 'schemas.yml#/Orders'
    Error:
      $ref: 'schemas.yml#/Error'

servers:
- description: SwaggerHub API Auto Mocking
  url: http://dc.utkin.xyz:8081
