CourierID:
  schema:
    type: string
  in: path
  name: courier_id
  required: true
  description: UUID of courier

OrderID:
  schema:
    type: string
  in: path
  name: order_id
  required: true
  description: UUID of order

GeoFilter:
  in: query
  style: form
  explode: true
  description: Search area
  name: filter
  schema:
    type: object
    oneOf:
    - $ref: 'schemas.yml#/Circle'
    - $ref: 'schemas.yml#/Box'
    - $ref: 'schemas.yml#/Zone'